name: metodos_transporte
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  drift: ^2.28.2
  drift_flutter: ^0.2.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  go_router: ^16.2.4
  google_fonts: ^6.3.2
  path_provider: ^2.1.5
  two_dimensional_scrollables: ^0.3.7

dev_dependencies:
  build_runner: ^2.7.1
  drift_dev: ^2.28.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - google_fonts/montserrat_alternates/